strings:
    inputs: Presentation/Presentation/Resource/Localization/Localizable.strings
    outputs:
        templateName: structured-swift4
        output: Presentation/Presentation/Generated/LocalizedString.swift
        params:
            enumName: LocalizedString
