strings:
    inputs: ReceiptScanner/ReceiptScanner/Resource/Localization/Localizable.strings
    outputs:
        templateName: structured-swift4
        output: ReceiptScanner/ReceiptScanner/Generated/LocalizedString.swift
        params:
            enumName: LocalizedString
