env:
    - PLATFORM="iOS Simulator,OS=14.4,name=iPhone 12"
language: objective-c
osx_image: xcode12.4
before_script:
    - set -o pipefail && brew install swiftlint
    - set -o pipefail && brew install swiftgen
script:
    - set -o pipefail && xcodebuild -workspace ReceiptScanner.xcworkspace -scheme ReceiptScanner -destination "platform=$PLATFORM" build test | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash)
